import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Calendar, 
  Save, 
  FileCode, 
  File as FileIcon, 
  Edit, 
  Sparkles, 
  CheckCircle,
  Clock,
  ArrowLeft,
  CheckSquare,
  BookOpen,
  Type,
  List,
  Loader2,
  Download
} from 'lucide-react';
import jsPDF from 'jspdf';

const SAMPLE_PAPER = {
  title: "Advanced Thermodynamics — Final Examination",
  questions: [
    { 
      id: 1, type: "Multiple Choice", difficulty: "Advanced",
      question: "Which of the following statements best describes the second law of thermodynamics in terms of entropy?",
      options: ["Entropy of an isolated system never decreases.", "Total entropy remains constant in irreversible processes.", "Heat can flow spontaneously from cold to hot bodies.", "Perfect crystals have zero entropy at room temperature."],
      answer: "Entropy of an isolated system never decreases."
    },
    {
      id: 2, type: "Multiple Choice", difficulty: "Advanced",
      question: "In a reversible adiabatic process, the change in entropy is always:",
      options: ["Positive", "Negative", "Zero", "Infinite"],
      answer: "Zero"
    },
    {
      id: 3, type: "Short Answer", difficulty: "Intermediate",
      question: "Explain the Gibbs Phase Rule and its significance in multi-component systems.",
      answer: "F = C - P + 2, where F is degrees of freedom, C is components, P is phases."
    },
    {
      id: 4, type: "Short Answer", difficulty: "Intermediate",
      question: "Distinguish between intensive and extensive properties with two examples for each.",
      answer: "Intensive: temperature, pressure. Extensive: volume, mass."
    },
    {
      id: 5, type: "Long Essay", difficulty: "Advanced",
      question: "Derive the Maxwell relations from the fundamental thermodynamic equations. Demonstrate how these relations are used to calculate changes in internal energy.",
      answer: ""
    }
  ]
};

const TypeBadge = ({ type }) => {
  const styles = {
    'Multiple Choice': 'bg-indigo-50 text-indigo-700 border-indigo-100',
    'Short Answer': 'bg-emerald-50 text-emerald-700 border-emerald-100',
    'Long Essay': 'bg-orange-50 text-orange-700 border-orange-100',
    'True / False': 'bg-purple-50 text-purple-700 border-purple-100',
    'True/False': 'bg-purple-50 text-purple-700 border-purple-100',
  };
  return (
    <span className={`px-2.5 py-1 rounded-lg text-[10px] font-bold uppercase tracking-wide border ${styles[type] || 'bg-slate-50 text-slate-600 border-slate-100'}`}>
      {type}
    </span>
  );
};

const groupQuestionsByType = (questions = []) => {
  const groups = {};
  questions.forEach(q => {
    const key = q.type || 'Other';
    if (!groups[key]) groups[key] = [];
    groups[key].push(q);
  });
  return groups;
};

const PaperView = () => {
  const navigate = useNavigate();
  const [paper, setPaper] = useState(null);
  const [isDemo, setIsDemo] = useState(false);
  const [showAnswers, setShowAnswers] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    const stored = sessionStorage.getItem('generatedPaper');
    if (stored) {
      try {
        const parsed = JSON.parse(stored);
        setPaper(parsed);
      } catch {
        setPaper(SAMPLE_PAPER);
        setIsDemo(true);
      }
    } else {
      setPaper(SAMPLE_PAPER);
      setIsDemo(true);
    }
  }, []);

  const exportPDF = () => {
    if (!paper) return;
    const doc = new jsPDF();
    const lineHeight = 10;
    let y = 20;
    const marginLeft = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const maxWidth = pageWidth - marginLeft * 2;

    const addText = (text, opts = {}) => {
      const { fontSize = 12, bold = false, color = [0, 0, 0], indent = 0 } = opts;
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', bold ? 'bold' : 'normal');
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(text, maxWidth - indent);
      lines.forEach(line => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(line, marginLeft + indent, y);
        y += lineHeight;
      });
    };

    addText(paper.title || 'Question Paper', { fontSize: 18, bold: true });
    y += 5;
    addText(`Generated by QuestGen AI • ${new Date().toLocaleDateString()}`, { fontSize: 10, color: [120, 120, 120] });
    y += 5;

    const groups = groupQuestionsByType(paper.questions);
    let globalIdx = 1;
    Object.entries(groups).forEach(([type, qs]) => {
      y += 5;
      addText(`Section: ${type}`, { fontSize: 13, bold: true, color: [53, 37, 205] });
      y += 2;
      qs.forEach(q => {
        y += 3;
        addText(`Q${globalIdx}. ${q.question}`, { fontSize: 11, bold: false, indent: 0 });
        if (q.options?.length) {
          q.options.forEach((opt, i) => {
            addText(`  ${String.fromCharCode(65 + i)}. ${opt}`, { fontSize: 10, color: [80, 80, 80], indent: 5 });
          });
        }
        globalIdx++;
      });
    });

    doc.save(`${paper.title || 'QuestGen-Paper'}.pdf`);
  };

  if (!paper) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="animate-spin text-indigo-600" size={36} />
      </div>
    );
  }

  const groups = groupQuestionsByType(paper.questions);
  const sectionLabels = {
    'Multiple Choice': 'Section A: Multiple Choice Questions',
    'Short Answer': 'Section B: Short Answer Questions',
    'Long Essay': 'Section C: Essay / Long Answer',
    'True / False': 'Section D: True or False',
    'True/False': 'Section D: True or False',
  };

  let globalQuestionNum = 0;

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      {/* Header Controls */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <button 
            onClick={() => navigate('/generate')}
            className="flex items-center gap-2 text-sm text-slate-500 hover:text-indigo-600 transition-colors mb-3 font-semibold"
          >
            <ArrowLeft size={16} />
            Back to Generator
          </button>
          <h1 className="text-3xl font-extrabold tracking-tight text-on-surface mb-1">{paper.title}</h1>
          <div className="flex flex-wrap items-center gap-3 mt-2">
            <p className="text-slate-500 flex items-center gap-2 text-sm font-medium">
              <Calendar size={14} />
              Generated {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </p>
            <span className="px-2 py-0.5 text-[10px] font-bold bg-indigo-50 text-indigo-600 rounded-full uppercase tracking-wider">
              {paper.questions?.length || 0} Questions
            </span>
            {isDemo && (
              <span className="px-2 py-0.5 text-[10px] font-bold bg-orange-50 text-orange-600 rounded-full uppercase tracking-wider border border-orange-100">
                Demo Paper
              </span>
            )}
          </div>
        </div>
        <div className="flex items-center gap-3 flex-wrap">
          <button 
            onClick={() => setShowAnswers(!showAnswers)}
            className={`flex items-center gap-2 px-5 py-2.5 rounded-xl font-semibold transition-all border shadow-sm text-sm ${
              showAnswers 
                ? 'bg-indigo-600 text-white border-indigo-600 shadow-indigo-200' 
                : 'bg-white text-on-surface border-slate-100'
            }`}
          >
            <CheckCircle size={16} />
            {showAnswers ? 'Hide Answers' : 'Show Answers'}
          </button>
          <button 
            onClick={exportPDF}
            className="flex items-center gap-2 px-5 py-2.5 hover:bg-slate-50 transition-all font-semibold text-indigo-600 border border-slate-100 bg-white rounded-xl shadow-sm text-sm"
          >
            <FileIcon size={16} />
            Export PDF
          </button>
        </div>
      </div>

      {/* Paper Canvas */}
      <div className="bg-white rounded-[1.5rem] sm:rounded-[3rem] p-6 sm:p-12 shadow-xl relative overflow-hidden border border-slate-50 print:shadow-none print:rounded-none">
        {/* Academic Header */}
        <div className="text-center mb-10 sm:mb-16 border-b border-slate-100 pb-8 sm:pb-12">
          <h2 className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400 mb-2 sm:mb-4">Academic Assessment • QuestGen AI</h2>
          <h3 className="text-2xl sm:text-4xl font-black text-indigo-900 mb-4">{paper.title}</h3>
          <div className="flex items-center justify-center gap-4 sm:gap-6 text-slate-500 text-[11px] sm:text-sm font-medium flex-wrap">
            <span className="flex items-center gap-1.5"><BookOpen size={14} /> {paper.questions?.length || 0} Questions</span>
            <span className="w-1.5 h-1.5 bg-slate-200 rounded-full hidden sm:block"></span>
            <span className="flex items-center gap-1.5"><Clock size={14} /> Est. {Math.round((paper.questions?.length || 20) * 2.5)} min</span>
            <span className="w-1.5 h-1.5 bg-slate-200 rounded-full hidden sm:block"></span>
            <span className="flex items-center gap-1.5"><Calendar size={14} /> {new Date().toLocaleDateString()}</span>
          </div>
        </div>

        {/* Sections */}
        {Object.entries(groups).map(([type, qs], sectionIdx) => (
          <section key={type} className={sectionIdx > 0 ? 'mb-12 pt-12 border-t border-slate-50' : 'mb-12'}>
            <div className="flex items-center justify-between mb-8">
              <h4 className="text-sm font-bold tracking-widest uppercase text-indigo-600 bg-indigo-50 px-4 py-1.5 rounded-full">
                {sectionLabels[type] || `Section: ${type}`}
              </h4>
              <span className="text-xs font-bold text-slate-300 uppercase tracking-tighter">{qs.length} Question{qs.length !== 1 ? 's' : ''}</span>
            </div>

            <div className="space-y-10">
              {qs.map((q) => {
                globalQuestionNum++;
                const num = globalQuestionNum;
                return (
                  <div key={q.id || num} className="group ml-4">
                    <div className="flex gap-4 items-start mb-4">
                      <span className="text-indigo-300 font-bold text-lg shrink-0 tabular-nums">{String(num).padStart(2, '0')}.</span>
                      <div className="flex-1">
                        <div className="flex items-start justify-between gap-4">
                          <p className="text-base font-semibold text-on-surface leading-relaxed flex-1">{q.question}</p>
                          <TypeBadge type={q.type} />
                        </div>

                        {/* Multiple Choice Options */}
                        {q.options?.length > 0 && (
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-5 ml-0">
                            {q.options.map((opt, i) => (
                              <div 
                                key={i} 
                                className={`p-4 rounded-xl text-sm border transition-all font-medium cursor-default ${
                                  showAnswers && opt === q.answer 
                                    ? 'bg-emerald-50 border-emerald-200 text-emerald-900' 
                                    : 'bg-slate-50 border-transparent hover:border-indigo-200 text-slate-600'
                                }`}
                              >
                                <span className="font-bold mr-2 text-indigo-500 whitespace-nowrap">{String.fromCharCode(65 + i)}.</span>
                                {opt}
                                {showAnswers && opt === q.answer && <span className="ml-2 text-emerald-600">✓</span>}
                              </div>
                            ))}
                          </div>
                        )}

                        {/* Short Answer line */}
                        {(q.type === 'Short Answer' || q.type === 'True / False' || q.type === 'True/False') && !q.options?.length && (
                          <div className="mt-4 space-y-2">
                            {showAnswers && q.answer ? (
                              <div className="p-4 bg-emerald-50 border border-emerald-100 rounded-xl text-sm text-emerald-800 font-medium">
                                <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-600 block mb-1">Answer</span>
                                {q.answer}
                              </div>
                            ) : (
                              <div className="h-12 border-b border-dashed border-slate-100"></div>
                            )}
                          </div>
                        )}

                        {/* Long Essay blank space */}
                        {q.type === 'Long Essay' && (
                          <div className="mt-4">
                            {showAnswers && q.answer ? (
                              <div className="p-4 bg-emerald-50 border border-emerald-100 rounded-xl text-sm text-emerald-800 font-medium">
                                <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-600 block mb-1">Model Answer</span>
                                {q.answer}
                              </div>
                            ) : (
                              <div className="space-y-3">
                                {[...Array(5)].map((_, i) => (
                                  <div key={i} className="h-8 border-b border-dashed border-slate-100"></div>
                                ))}
                                <p className="text-xs text-slate-400 italic font-medium flex items-center gap-2">
                                  <Clock size={12} /> Expected length: 400–600 words
                                </p>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>
        ))}

        {/* Footer */}
        <div className="mt-20 pt-12 border-t border-slate-50 flex justify-between italic text-slate-300 text-xs font-medium uppercase tracking-[0.1em]">
          <p>QuestGen AI • Academic Intelligence Platform</p>
          <p>End of Paper</p>
        </div>
      </div>

      {/* Floating Actions */}
      <div className="mt-12 flex items-center justify-center gap-4 flex-wrap">
        <button 
          onClick={() => navigate('/generate')}
          className="bg-indigo-50 text-indigo-700 px-8 py-3.5 rounded-2xl font-bold flex items-center gap-2 hover:bg-indigo-100 transition-all shadow-sm"
        >
          <Edit size={20} />
          Generate New Paper
        </button>
        <button 
          onClick={() => navigate('/bank')}
          className="bg-gradient-to-br from-primary to-primary-container text-white px-10 py-3.5 rounded-2xl font-bold flex items-center gap-2 shadow-lg hover:scale-[1.05] active:scale-[0.95] transition-all"
        >
          <Save size={20} />
          Save to Question Bank
        </button>
      </div>

      {/* Success Toast */}
      {saved && (
        <div className="fixed bottom-8 right-8 bg-emerald-600 text-white px-6 py-4 rounded-2xl shadow-2xl flex items-center gap-4 animate-in fade-in slide-in-from-bottom-5 z-50">
          <div className="w-10 h-10 bg-white/20 rounded-full flex items-center justify-center">
            <CheckCircle size={24} />
          </div>
          <div>
            <p className="font-bold leading-none">Paper Saved!</p>
            <p className="text-xs text-white/80 mt-1">Added to your Question Bank</p>
          </div>
        </div>
      )}
    </div>
  );
};

export default PaperView;
